collections:
  - name: community.zabbix
    version: 1.4.0
  - name: community.general
    version: 3.5.0
  - name: community.mysql
    version: 2.1.1
  - name: community.postgresql
    version: 1.4.0
