---
- name: Using General, Buildin collection
  hosts: fbsd-vagrant
  remote_user: root
  collections:
    - community.general
    - ansible.builtin
  
  tasks:
  - name: Install package zabbix5-agent
    pkgng:
      name: zabbix5-agent
      state: present

  - name: Enable service zabbix_agentd, and not touch the state
    service:
      name: zabbix_agentd
      enabled: yes

  - name: Copy sample zabbix_agentd.conf
    copy:
      src: ./conf/zabbix5_agentd.conf.sample
      dest: /usr/local/etc/zabbix5/zabbix_agentd.conf
      owner: root
      group: wheel

  - name: Edit  agent hostname
    lineinfile:
      path: /usr/local/etc/zabbix5/zabbix_agentd.conf
      regexp: ^Hostname=.*
      line: Hostname={{ ansible_fqdn }}

  - name: Edit agent server
    lineinfile:
      path: /usr/local/etc/zabbix5/zabbix_agentd.conf
      regexp: ^Server=.*
      line: Server={{ zabbix_server }}

  - name: Start service zabbix5-agent, if not started
    service:
      name: zabbix_agentd
      state: started